name: Git-Hub-Profile-AtCoder

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-Git-Hub-Profile-AtCoder
    steps:
      - uses: actions/checkout@v3
      - uses: kinakomoch7/git-hub-profile-atcoder@v0.2.1
        env:
          USER_NAME: Ishi_eenn
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          if git diff --cached --exit-code; then
            echo "No changes to commit."
          else
            git commit -m "generated"
            git push
          fi
